local mt = {}

--------------------------------------------------------------------------------------
-- 整数存档（反作弊）
INT_STORAGE = {}
OLD_INT_STORAGE = {}
BOOL_STORAGE = {}

--------------------------------------------------------------------------------------
-- 混杂
OLD_INT_STORAGE.MISC_NUMBER_1 = 'MISCN1'
OLD_INT_STORAGE.OUTFIT_NUMBER_1 = 'OUTFITN1'
BOOL_STORAGE.MISC_BOOL_1 = 'MISCB1'

--------------------------------------------------------------------------------------
-- 时间戳
INT_STORAGE.UNIX_DAY = 'UNIXDAY'

--------------------------------------------------------------------------------------
-- 游戏活跃度 YXHYD
INT_STORAGE.ACTIVITY_EXP = 'YXHYD'
INT_STORAGE.ACTIVITY_EXP_DAY = 'YXHYDD'
BOOL_STORAGE.ACTIVITY_EXP_REWARD = 'YXHYDR'

--------------------------------------------------------------------------------------
-- 天赋存档槽
BOOL_STORAGE.TALENT_STORAGE_1 = 'TFCDC1'
BOOL_STORAGE.TALENT_STORAGE_2 = 'TFCDC2'
BOOL_STORAGE.TALENT_STORAGE_3 = 'TFCDC3'
BOOL_STORAGE.TALENT_STORAGE_4 = 'TFCDC4'

--------------------------------------------------------------------------------------
-- 成就
BOOL_STORAGE.MAP_LV = 'MAPLV'
MAP_LV_PRESENT_LIST = 'MAPLV_PRESENT'
BOOL_STORAGE.GAME_LV = 'GAMELV'
GAME_LV_PRESENT_LIST = 'GAMELV_PRESENT'
BOOL_STORAGE.WIN_ACHIEVEMENT_1 = 'WINACHI1'
BOOL_STORAGE.WELFARE = 'WELFARE'
WELFARE_PRESENT_LIST = 'WELFARE_PRESENT'
BOOL_STORAGE.GUILD = 'GUILD'
BOOL_STORAGE.GAME_ACHIEVEMENT_1 = 'GAMEACHI1'
BOOL_STORAGE.GAME_ACHIEVEMENT_2 = 'GAMEACHI2'
GAME_ACHIEVEMENT_PRESENT_LIST = 'GAMEACHI_PRESENT'
BOOL_STORAGE.HIDDEN_WELFARE = 'GAMEACHI_HIDDEN'
OLD_INT_STORAGE.RANDOM_CANGPIN_1_1 = 'RANDOMCANGPIN11'
OLD_INT_STORAGE.RANDOM_CANGPIN_1_2 = 'RANDOMCANGPIN12'
OLD_INT_STORAGE.RANDOM_CANGPIN_1_3 = 'RANDOMCANGPIN13'
OLD_INT_STORAGE.RANDOM_CANGPIN_1_4 = 'RANDOMCANGPIN14'
OLD_INT_STORAGE.RANDOM_CANGPIN_1_5 = 'RANDOMCANGPIN15'
OLD_INT_STORAGE.RANDOM_CANGPIN_1_6 = 'RANDOMCANGPIN16'
OLD_INT_STORAGE.RANDOM_CANGPIN_1_7 = 'RANDOMCANGPIN17'
OLD_INT_STORAGE.RANDOM_CANGPIN_1_8 = 'RANDOMCANGPIN18'
OLD_INT_STORAGE.RANDOM_CANGPIN_2_1 = 'RANDOMCANGPIN21'
OLD_INT_STORAGE.RANDOM_CANGPIN_2_2 = 'RANDOMCANGPIN22'
OLD_INT_STORAGE.RANDOM_CANGPIN_2_3 = 'RANDOMCANGPIN23'
OLD_INT_STORAGE.RANDOM_CANGPIN_2_4 = 'RANDOMCANGPIN24'
OLD_INT_STORAGE.RANDOM_CANGPIN_2_5 = 'RANDOMCANGPIN25'
OLD_INT_STORAGE.RANDOM_CANGPIN_2_6 = 'RANDOMCANGPIN26'
OLD_INT_STORAGE.RANDOM_CANGPIN_2_7 = 'RANDOMCANGPIN27'
OLD_INT_STORAGE.RANDOM_CANGPIN_2_8 = 'RANDOMCANGPIN28'
OLD_INT_STORAGE.RANDOM_CANGPIN_3_1 = 'RANDOMCANGPIN31'
OLD_INT_STORAGE.RANDOM_CANGPIN_3_2 = 'RANDOMCANGPIN32'
OLD_INT_STORAGE.RANDOM_CANGPIN_3_3 = 'RANDOMCANGPIN33'
OLD_INT_STORAGE.RANDOM_CANGPIN_3_4 = 'RANDOMCANGPIN34'
OLD_INT_STORAGE.RANDOM_CANGPIN_3_5 = 'RANDOMCANGPIN35'
OLD_INT_STORAGE.RANDOM_CANGPIN_3_6 = 'RANDOMCANGPIN36'
OLD_INT_STORAGE.RANDOM_CANGPIN_3_7 = 'RANDOMCANGPIN37'
OLD_INT_STORAGE.RANDOM_CANGPIN_3_8 = 'RANDOMCANGPIN38'

--------------------------------------------------------------------------------------
INT_STORAGE.CHAPTER_COLLECTION_COUNT = 'CPCLCOUNT' -- 章节藏品
INT_STORAGE.CHAPTER_COLLECTION_COUNT_DAY = 'CPCLCOUNTD' -- 每日章节藏品
--------------------------------------------------------------------------------------
-- 碎片
INT_STORAGE.HERO_FRAG_R = 'HFRAGR'
INT_STORAGE.HERO_FRAG_SR = 'HFRAGSR'
INT_STORAGE.HERO_FRAG_SSR = 'HFRAGSSR'

INT_STORAGE.HERO_EXCHANGE_FRAG_SR = 'HEXFRAGSR'
INT_STORAGE.HERO_EXCHANGE_FRAG_SSR = 'HEXFRAGSSR'

--------------------------------------------------------------------------------------
-- 英雄
BOOL_STORAGE.HERO_R ='HEROR'
BOOL_STORAGE.HERO_SR ='HEROSR'
BOOL_STORAGE.HERO_SSR ='HEROSSR'

BOOL_STORAGE.HERO_PHASE_REWARD ='HEROPHASE'
INT_STORAGE.HERO_TOTAL = 'HEROTOTAL' --仅用于平台成就

--------------------------------------------------------------------------------------
-- 藏品
BOOL_STORAGE.COLLECT_1_BLUE ='COLLECT1'
BOOL_STORAGE.COLLECT_2_PURPLE ='COLLECT2'
BOOL_STORAGE.COLLECT_3_ORANGE ='COLLECT3'
BOOL_STORAGE.COLLECT_4_RED ='COLLECT4'
BOOL_STORAGE.COLLECT_5_PINK ='COLLECT5'
BOOL_STORAGE.COLLECT_6_GOLDEN ='COLLECT6'

BOOL_STORAGE.COLLECT_1_BLUE_NEW ='COLLECT1NEW'
BOOL_STORAGE.COLLECT_2_PURPLE_NEW ='COLLECT2NEW'
BOOL_STORAGE.COLLECT_3_ORANGE_NEW ='COLLECT3NEW'
BOOL_STORAGE.COLLECT_4_RED_NEW ='COLLECT4NEW'

INT_STORAGE.COLLECT_SHARD = 'COLLECTSHARD'
INT_STORAGE.COLLECT_SHARD_DAY_MAX = 'COLLECTSHARDDMAX'
INT_STORAGE.COLLECT_SHARD_MAX = 'COLLECTSHARDM' -- 藏品碎片总和
INT_STORAGE.COLLECT_TOTAL = 'COLLECTTOTAL' --仅用于平台成就

COLLECTION_PRESENT_LIST = 'collection_present_list'

--------------------------------------------------------------------------------------
-- 每日活动
BOOL_STORAGE.DAILY_QUEST = 'DAYQUEST'
INT_STORAGE.DAILY_BOSS_KILL = 'DBOSSKILL'
INT_STORAGE.DAILY_ONLINE_TIME = 'DAILYONLINETIME'
INT_STORAGE.PLATFORM_SIGN = 'PLATFORMSIGN'
INT_STORAGE.DAILY_FINAL_BOSS_COLLECTION_GET = 'DFBOSSCOLLECT'
INT_STORAGE.DAILY_ARCH_EQUIP_GET = 'DFAEQUIPGET'
INT_STORAGE.DAILY_HERO_FRAG_GET = 'DHEROFRAG'
INT_STORAGE.DAILY_DROP_DUST = 'DDROPDUST' -- 日掉落粉尘
INT_STORAGE.ONLINE_TIME_520 = 'ONLINETIME520'

DAY_MAX_HERO_FRAG = 60

--------------------------------------------------------------------------------------
-- 登录14日
BOOL_STORAGE.LOGIN_14 = 'LOGIN14'

--------------------------------------------------------------------------------------
-- 钓鱼
BOOL_STORAGE.DIAOYU = 'DIAOYU'
BOOL_STORAGE.JINLI = 'JINLI'
INT_STORAGE.DIAOYUSCORE = 'DIAOYUSCORE' -- 钓鱼积分
INT_STORAGE.JINLISCORE = 'JINLISCORE' -- 锦鲤积分
DIAOYU_PRESENT_LIST = "DIAOYU_PRESENT"
JINLI_PRESENT_LIST  = "JINLI_PRESENT"

INT_STORAGE.DIAOYUSCORE_DAY = "DCRO1DAY"
INT_STORAGE.JINLISCORE_DAY = "DCRO2DAY"
--------------------------------------------------------------------------------------
-- 通行证
BOOL_STORAGE.BATTLEPASSPOOR = 'BATTLEPASSPOOR'
BOOL_STORAGE.BATTLEPASSRICH = 'BATTLEPASSRICH'

BOOL_STORAGE.BATTLEPASSPOOR2 = 'BATTLEPASSPOOR2'
BOOL_STORAGE.BATTLEPASSRICH2 = 'BATTLEPASSRICH2'
INT_STORAGE.BATTLEPASS2_DAY = "BATTLEPASSD2"

BOOL_STORAGE.BATTLEPASSPOOR3 = 'BATTLEPASSPOOR3'
BOOL_STORAGE.BATTLEPASSRICH3 = 'BATTLEPASSRICH3'
INT_STORAGE.BATTLEPASS3_DAY = "BATTLEPASSD3"

--------------------------------------------------------------------------------------
-- 签到
INT_STORAGE.NEW_GAME_SIGN = 'NGSIGN'
INT_STORAGE.NEW_GAME_SIGN_DAY = 'NGSIGND'
BOOL_STORAGE.NEW_GAME_SIGN_REWARD = 'NGSIGNR'

--------------------------------------------------------------------------------------
-- 森林晶核
INT_STORAGE.FOREST_LUMBER = 'CPCRY1'
INT_STORAGE.FOREST_LUMBER_DAY = 'CPCRY1D'
BOOL_STORAGE.FOREST_LUMBER_REWARD = 'CPCRY1R'
BOOL_STORAGE.FOREST_LUMBER_STORE = 'CPCRY1S'

--------------------------------------------------------------------------------------
-- 商城道具
BOOL_STORAGE.STORE_REWARD_1 = 'STORE1'
BOOL_STORAGE.SHINE = 'SHINE'

STORE_PRESENT_LIST = 'STORE_PRESENT'
--------------------------------------------------------------------------------------
-- 通关次数
INT_STORAGE.WIN_COUNT_DAY = 'TGCSD' -- 通关次数（日上限）
-- INT_STORAGE.WIN_COUNT_1_1 = 'TGCS11' -- 通关次数1-1
-- INT_STORAGE.WIN_COUNT_1_2 = 'TGCS12' -- 通关次数1-2
-- INT_STORAGE.WIN_COUNT_1_3 = 'TGCS13' -- 通关次数1-3
-- INT_STORAGE.WIN_COUNT_1_4 = 'TGCS14' -- 通关次数1-4
-- INT_STORAGE.WIN_COUNT_1_5 = 'TGCS15' -- 通关次数1-5
-- INT_STORAGE.WIN_COUNT_1_6 = 'TGCS16' -- 通关次数1-6
-- INT_STORAGE.WIN_COUNT_1_7 = 'TGCS17' -- 通关次数1-7
-- INT_STORAGE.WIN_COUNT_1_8 = 'TGCS18' -- 通关次数1-8

-- INT_STORAGE.CANGPIN_WIN_COUNT_1_1 = 'CPTGCS11' -- 藏品通关次数1-1
-- INT_STORAGE.CANGPIN_WIN_COUNT_1_2 = 'CPTGCS12' -- 藏品通关次数1-2
-- INT_STORAGE.CANGPIN_WIN_COUNT_1_3 = 'CPTGCS13' -- 藏品通关次数1-3
-- INT_STORAGE.CANGPIN_WIN_COUNT_1_4 = 'CPTGCS14' -- 藏品通关次数1-4
-- INT_STORAGE.CANGPIN_WIN_COUNT_1_5 = 'CPTGCS15' -- 藏品通关次数1-5
-- INT_STORAGE.CANGPIN_WIN_COUNT_1_6 = 'CPTGCS16' -- 藏品通关次数1-6
-- INT_STORAGE.CANGPIN_WIN_COUNT_1_7 = 'CPTGCS17' -- 藏品通关次数1-7
-- INT_STORAGE.CANGPIN_WIN_COUNT_1_8 = 'CPTGCS18' -- 藏品通关次数1-8


INT_STORAGE.WIN_GAME_NOT_DEAD = 'TGBS1'--不死通关
INT_STORAGE.WIN_COUNT_TOTAL = 'TGCSZG' -- 通关次数总共
TONGGUAN_ACHIEVEMENT_PRESENT_LIST= 'TONGGUAN_PRESENT'
TONGGUANCANGPIN_ACHIEVEMENT_PRESENT_LIST= 'TONGGUANCANGPIN_PRESENT'
-- 统计次数
INT_STORAGE.KILL_BOSS_TOTAL = 'ZGSSBS' -- 总共杀死boss
INT_STORAGE.KILL_BOSS_TOTAL_DAY = 'ZGSSBSD' -- 总共杀死boss（日上限）

-- 通关星星
BOOL_STORAGE.WIN_DIFF_STAR_CHAPTER_1 = 'TGXS1' -- 通关星数章节一
BOOL_STORAGE.CHAPTER_1_STAR_REWARDS = 'TGXSJLC1' -- 通关星数奖励章节一

BOOL_STORAGE.WIN_DIFF_STAR_CHAPTER_2 = 'TGXS2' -- 通关星数章节二
BOOL_STORAGE.CHAPTER_2_STAR_REWARDS = 'TGXSJLC2' -- 通关星数奖励章节二

BOOL_STORAGE.WIN_DIFF_STAR_CHAPTER_3 = 'TGXS3' -- 通关星数章节三
BOOL_STORAGE.CHAPTER_3_STAR_REWARDS = 'TGXSJLC3' -- 通关星数奖励章节三

BOOL_STORAGE.WIN_DIFF_STAR_CHAPTER_4 = 'TGXS4' -- 通关星数章节四
BOOL_STORAGE.CHAPTER_4_STAR_REWARDS = 'TGXSJLC4' -- 通关星数奖励章节四
--------------------------------------------------------------------------------------
BOOL_STORAGE.CHAPTER_ENDLESS_ACHIEVEMENT = 'WJMSJL1' -- 无尽模式成就
ENDLESS_ACHIEVEMENT_PRESENT_LIST = 'ENDLESSACHI_PRESENT'
--------------------------------------------------------------------------------------
-- 通关次数
INT_STORAGE.DAILY_COMPLETE_REWARD_ONCE = "DCRO1"
INT_STORAGE.DAILY_COMPLETE_REWARD_TWICE = "DCRO2"
INT_STORAGE.DAILY_COMPLETE_REWARD_THREE = "DCRO3"
INT_STORAGE.DAILY_COMPLETE_REWARD_FIVE = "DCRO5"
INT_STORAGE.DAILY_COMPLETE_REWARD_EIGHT = "DCRO8"
INT_STORAGE.DAILY_COMPLETE_REWARD_DAY_MAX1 = 'DCRODM1'
INT_STORAGE.DAILY_COMPLETE_REWARD_DAY_MAX2 = 'DCRODM2'
INT_STORAGE.DAILY_COMPLETE_REWARD_DAY_MAX3 = 'DCRODM3'
INT_STORAGE.DAILY_COMPLETE_REWARD_DAY_MAX5 = 'DCRODM5'
INT_STORAGE.DAILY_COMPLETE_REWARD_DAY_MAX8 = 'DCRODM8'
INT_STORAGE.HUNT_POINT = 'SLMSJF1'
BOOL_STORAGE.HUNT_LV_REWARDS = 'SLDJJL'
HUNT_LV_PRESENT_LIST = 'SLMSDJJL1'

INT_STORAGE.OUTFIT_SHARD = 'OUTFITS' -- 套装碎片
INT_STORAGE.OUTFIT_SHARD_DAY_MAX = 'OUTFITSDMAX' -- 套装碎片日上限
INT_STORAGE.OUTFIT_EXCHANGE_1_DAY = 'OUTFITEX1' -- 套装兑换1000日记录
INT_STORAGE.OUTFIT_EXCHANGE_2_DAY = 'OUTFITEX2' -- 套装兑换4000日记录
INT_STORAGE.OUTFIT_EXCHANGE_3_DAY = 'OUTFITEX3' -- 套装兑换10000日记录
INT_STORAGE.OUTFIT_EXCHANGE_4_DAY = 'OUTFITEX4' -- 套装兑换16000日记录

--------------------------------------------------------------------------------------
INT_STORAGE.OCTOBER_SHARD_GET = 'OCTBSG' -- 灯笼获取
INT_STORAGE.OCTOBER_SHARD_DAY_MAX = 'OCTBSDMAX' -- 灯笼日上限
INT_STORAGE.OCTOBER_SHARD_USED = 'OCTBSGU' -- 灯笼使用
--------------------------------------------------------------------------------------
-- 老带新
INT_STORAGE.DAIXINCISHU = 'LDXLWJCS'
INT_STORAGE.BEIDAIXINCISHU = 'BLDXLWJCS'
--------------------------------------------------------------------------------------
INT_STORAGE.ONLINE_TIME_60MIN_COUNT = 'ZXLSFZMTCS1'
INT_STORAGE.ONLINE_TIME_60MIN_COUNT_DAY_MAX = 'ZXLSFZMTCSDAYMAX1'
BOOL_STORAGE.ONLINE_TIME_60MIN_REWARD = 'ZXLSFZMTJL1'
ONLINE_TIME_60MIN_REWARD_PRESENT_LIST = 'ONLINE_TIME_60MIN_REWARD_PRESENT_LIST'

BOOL_STORAGE.BAN_MEMORY_1 = 'BANMEM1' -- ban专精

INT_STORAGE.CHEAT = 'CHEAT' -- 作弊
INT_STORAGE.CHEAT2 = 'CHEAT2' -- 作弊2
--------------------------------------------------------------------------------------
-- 成长神器

BOOL_STORAGE.GROWING_EQUIPMENT = 'CZSQJL1'
INT_STORAGE.GROWING_EQUIPMENT_EXP = 'CZSQZJY1' 
HUNTING_MARK_RANDOM_STATS_PRESENT_LIST = 'HMRSPL1'
OLD_INT_STORAGE.RANDOM_STATS_HUNTING_MARK = 'RANDOMHM1'
INT_STORAGE.GROWING_EQUIPMENT_EXP_DAY_MAX = 'CZSQZJYDAYMAX1' 
INT_STORAGE.GROWING_EQUIPMENT_AFFIX = 'CZSQAFFIX' 
INT_STORAGE.GROWING_EQUIPMENT_AFFIX_DAY_MAX = 'CZSQAFFIXDAY' 

--------------------------------------------------------------------------------------
-- 商城堆叠
INT_STORAGE.STORE_CANGBAOMIXIA = 'STORESTACK6' --藏宝密匣
--------------------------------------------------------------------------------------
-- 混乱模式
BOOL_STORAGE.CHAOS_MODE_ARCH_REWARDS = 'CHAOSMODE1'
CHAOS_MODE_ARCH_REWARDS_PRESENT_LIST = 'CHAOSMARPL1'
INT_STORAGE.CHAOS_MODE_COUNT = 'CHAOSMODECOUNT1' --混乱模式次数
--------------------------------------------------------------------------------------
CHILD_REWARDS_PRESENT_LIST = 'CHILD_REWARDS_PRESENT'
INT_STORAGE.CHILD_REWARDS_COUNT = 'CHILD_REWARDS_COUNT'
INT_STORAGE.CHILD_REWARDS_DAY_MAX = 'CHILD_REWARDS_DAY_MAX'
OLD_INT_STORAGE.CHILD_REWARDS_LIST_1 = 'CHILD_REWARDSL1'
OLD_INT_STORAGE.CHILD_REWARDS_LIST_2 = 'CHILD_REWARDSL2'
BOOL_STORAGE.CHILD_REWARDS = 'CHILD_REWARDSBOOL'
CHILD_REWARDS_PRESENT_LIST_LAYERS = 'CHILD_REWARDS_PRESENT_LIST'
--------------------------------------------------------------------------------------
DUANWU_REWARDS_PRESENT_LIST = 'DUANWU_REWARDS_PRESENT'
BOOL_STORAGE.DUANWU_REWARDS = 'DUANWU_REWARDSBOOL'
INT_STORAGE.DUANWU_POINT = 'DUANWU_POINT'
INT_STORAGE.DUANWU_POINT_MAX = 'DUANWU_POINT_MAX'
--------------------------------------------------------------------------------------
-- 老带新
INT_STORAGE.ROOKIE_POINT = 'LDXRKPT1'
INT_STORAGE.OLDPLAYERPOINT = 'LDXOPP1'
INT_STORAGE.LDX_POINT_DAY_MAX = 'LDX_POINT_MAX'
BOOL_STORAGE.LDX_REWARDS = 'LDX_REWARDSBOOL'
BOOL_STORAGE.LDX_OLD_REWARDS = 'LDX_OLD_REWARDS'
LDX_REWARDS_PRESENT_LIST = 'LDX_REWARDS_PRESENT'
--------------------------------------------------------------------------------------
-- 元素深渊
-- 通关次数
INT_STORAGE.ELEMENT_ABYSS_PUZZLE_DAY = 'eleabyssgw1d'
INT_STORAGE.ELEMENT_ABYSS_PUZZLE_DAY_MAX = 'eleabyssgw1dm'
--------------------------------------------------------------------------------------
--BOSS
OLD_INT_STORAGE.ELEMENT_ABYSS_BOSS_ZIRAN = 'eleabyssboss1'
OLD_INT_STORAGE.ELEMENT_ABYSS_BOSS_DADI = 'eleabyssboss2'
OLD_INT_STORAGE.ELEMENT_ABYSS_BOSS_LEIDIAN = 'eleabyssboss3'
OLD_INT_STORAGE.ELEMENT_ABYSS_BOSS_HANBING = 'eleabyssboss4'
OLD_INT_STORAGE.ELEMENT_ABYSS_BOSS_ANHEI = 'eleabyssboss5'
OLD_INT_STORAGE.ELEMENT_ABYSS_BOSS_HUOYAN = 'eleabyssboss6'
OLD_INT_STORAGE.ELEMENT_ABYSS_BOSS_CHAOXI = 'eleabyssboss7'
--------------------------------------------------------------------------------------
-- 系数
EXTRA_FOREST_EXP = fc.makeConstId({
    name = '额外森林经验',
})

SPEED_UP_FOREST_EXP = fc.makeConstId({
    name = '森林经验获取加速',
    isPct = true,
})
--------------------------------------------------------------------------------------
return mt
